// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl_QvpRmpgqJ0BIUUBl3Sw7N-HgIoOhWM',
    appId: '1:1017324137334:web:a66aacdeb415dcf0baa857',
    messagingSenderId: '1017324137334',
    projectId: 'chuaynooduay',
    authDomain: 'chuaynooduay.firebaseapp.com',
    storageBucket: 'chuaynooduay.firebasestorage.app',
    measurementId: 'G-7603CDQ1LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh1lr1nT8ZjSRTz52rovOf_WEojW7ulgM',
    appId: '1:1017324137334:android:2b6990a69a131006baa857',
    messagingSenderId: '1017324137334',
    projectId: 'chuaynooduay',
    storageBucket: 'chuaynooduay.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC66surzVSUB6H8rI2g1oEjbv9ViETSOE4',
    appId: '1:1017324137334:ios:78135dc3d0a3576ebaa857',
    messagingSenderId: '1017324137334',
    projectId: 'chuaynooduay',
    storageBucket: 'chuaynooduay.firebasestorage.app',
    iosClientId: '1017324137334-acahih38upcl99oo3lr97qpjmba94731.apps.googleusercontent.com',
    iosBundleId: 'com.example.weAreReady',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC66surzVSUB6H8rI2g1oEjbv9ViETSOE4',
    appId: '1:1017324137334:ios:78135dc3d0a3576ebaa857',
    messagingSenderId: '1017324137334',
    projectId: 'chuaynooduay',
    storageBucket: 'chuaynooduay.firebasestorage.app',
    iosClientId: '1017324137334-acahih38upcl99oo3lr97qpjmba94731.apps.googleusercontent.com',
    iosBundleId: 'com.example.weAreReady',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl_QvpRmpgqJ0BIUUBl3Sw7N-HgIoOhWM',
    appId: '1:1017324137334:web:149ec04573811fe0baa857',
    messagingSenderId: '1017324137334',
    projectId: 'chuaynooduay',
    authDomain: 'chuaynooduay.firebaseapp.com',
    storageBucket: 'chuaynooduay.firebasestorage.app',
    measurementId: 'G-TDMD07Q5B1',
  );
}
